<form action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud']; ?>&task=updateTopic" method="POST">
<!-- <form action="<?= $tplVars['WWW_URL']; ?>index.php" method="POST"> -->
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center my-4">
        <a class="btn btn-outline-secondary" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud']; ?>&task=index"><i class="fa fa-times"></i> Annuler les modifications</a>
        <button class="btn btn-primary"><i class="fa fa-check"></i> Valider et enregistrer</button>
    </div>

    <fieldset class="p-3 bg-light">
        <div class="form-group row">
            <label for="name" class="col-sm-3 col-form-label">Nom</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="name" name="name" value="">
            </div>
        </div>
    </fieldset>

</form>