<section class="quiz box about">
    <div class="detail-categorie">
        <h1>A propos de QuiZ by ACo - 2021</h1>

        <p><span class="golden-text">U</span><span class="purple-text">n</span> site web ludique réalisé en janvier et février 2021 pour le projet professionnel de fin de formation Développeur Web à la 3W Academy à Nantes.</p>
        <p>Technos utilisés :</p>
        <ul>
            <li>HTML 5</li>
            <li>Préprocesseur SASS en SCSS</li>
            <li>Javascript ES6 pour les réponses, la navbar, et les notifications.</li>

            <li>Bootstrap pour le BackOffice</li>
            <li>PHP 7.4 pour le back, c'est à dire aller chercher les questions, les topics, les profils utilisateurs dans la base de données, prendre les informations des formulaires, les vérifier et les stocker, aller afficher et stocker les scores.</li>
            <li>MySQL 5 pour la base de données, ci-jointe :</li>
        </ul>
        <img class="bdd" src="assets/images/bddQuiz.png" alt="image de la base de données du site">






    </div>

</section>