<section class="quiz box about">
    <div class="detail-categorie">
        <h1>A propos de QuiZ by ACo - 2021</h1>
        <p><span class="golden-text">S</span>it<span class="purple-text">e</span> web ludique à but non lucratif réalisé
            par <a href="https://www.linkedin.com/in/alexandre-connangle-6221a558/">Alexandre Code</a> en
            janvier/février puis repris en mai 2021 pour le projet professionnel de fin de formation Développeur Web
            Full Stack équivalent BAC+2 à la 3W Academy à Nantes.</p>
        <p>Technologies utilisées :</p>
        <p>Front ( le visuel )</p>
        <ul>
            <li>HTML 5</li>
            <li>Préprocesseur SASS en SCSS</li>
            <li>Javascript ES6.</li>
            <li>Bootstrap uniquement pour le BackOffice ("façe cachée" du site uniquement accessible aux
                Administrateurs)</li>
        </ul>
        <p>Back ( la machinerie derrière )</p>
        <ul>
            <li>PHP 7.4 pour tout le système fonctionnel derrière ce qui est affiché, comme aller chercher les
                questions, les topics, les profils utilisateurs dans la base de données, prendre les informations des
                formulaires, les vérifier et les stocker, aller afficher et mettre à jour les scores, les calculs des
                scores etc.</li>
            <li>MySQL 5 pour la base de données, ci-jointe :</li>
        </ul>
        <img class="bdd" src="assets/images/bddQuiz.png" alt="image de la base de données du site">
        <p>Version 1.0 -> 14/02/2021</p>
        <p>Version 1.1 -> 28/05/2021, grosse maj générale, corrections de bugs, un utilisateur peut maintenant changer
            son avatar son pseudo ou son mail dans Mon Compte / Mes Informations, correction erreur des scores parfois
            décalés si pas tous joués, correction avatars parfois ne correspondaient pas avec celui choisi (décalage de
            1), code allégé, maj de l'accueil, les scores ne peuvent plus dépasser 100%, les modales sont "scrollables"
            pour les petits écrans, les mdp des formulaires sont masqués et doivent faire 5 caractières minimum,
            normalize.css ajouté, header amélioré se connecter et s'inscrire ne sont plus disponibles quand
            l'utilisateur est connecté, inversement deconnexion n'est pas disponible quand l'utilisateur n'est pas
            connecté, changements visuels 100vh en min-height sur le body, fond gradient, overflow corrigé sur la box
            commentaires, espace des images prévu avant que les images chargent, shadows améliorés, ergonomie du menu du
            header simplifiée.</p>
    </div>
</section>