<section class="quiz box about">
    <div class="detail-categorie">
        <h1>A propos de QuiZ by ACo - 2021</h1>
        <p><span class="golden-text">S</span>it<span class="purple-text">e</span> web ludique à but non lucratif réalisé par <a href="https://www.linkedin.com/in/alexandre-connangle-6221a558/">Alexandre Code</a> en janvier et février 2021 pour le projet professionnel de fin de formation Développeur Web à la 3W Academy à Nantes.</p>
        <p>Technologies utilisées :</p>
        <p>Front ( le visuel )</p>
        <ul>
            <li>HTML 5</li>
            <li>Préprocesseur SASS en SCSS</li>
            <li>Javascript ES6.</li>
            <li>Bootstrap uniquement pour le BackOffice ("façe cachée" du site uniquement accessible aux Administrateurs)</li>
        </ul>
        <p>Back ( la machinerie derrière )</p>
        <ul>
            <li>PHP 7.4 pour tout le système fonctionnel derrière ce qui est affiché, comme aller chercher les questions, les topics, les profils utilisateurs dans la base de données, prendre les informations des formulaires, les vérifier et les stocker, aller afficher et mettre à jour les scores, les calculs si besoin etc.</li>
            <li>MySQL 5 pour la base de données, ci-jointe :</li>
        </ul>
        <img class="bdd" src="assets/images/bddQuiz.png" alt="image de la base de données du site">
        <p>Version 1.0 -> 14/02/2021</p>
    </div>
</section>