<section class="quiz box goldenBook">
    <h2>Livre d'Or</h2>
    <div>
        <?php foreach ($tplVars['commentaries'] as $key => $commentary) : ?>
            <blockquote>
                <cite>"<?= $commentary["Content"]; ?>"</cite>
                <p>écrit le <?= $commentary['Created_at']; ?> par <?= $tplVars['commentaryCreatedBy'][$key] ?></p>
            </blockquote>
        <?php endforeach; ?>
        
        <!-- Section pour mettre un ocmmentaire -->
        <form method="post" action="<?= $tplVars['WWW_URL']; ?>index.php?controller=commentary&task=commentarySent">
            <textarea name="commentary" id="commentary" cols="30" rows="10"></textarea>
            <button type="Submit">Envoyer</button>
        </form>
    </div>
</section>