<section class="quiz box goldenBook">
    <h2>Livre d'Or</h2>

    <div>


        <?php foreach ($tplVars['commentaries'] as $key => $commentary) : ?>

            <blockquote>
                <cite>"<?= $commentary["Content"]; ?>"</cite>

                <!-- permet de choper la date, en enlevant l'heure -->
                <?php $date = explode(" ", $commentary['Created_at']); ?>

                <p>créé le <?= $date[0]; ?> par <?= $tplVars['commentaryCreatedBy'][$key] ?></p>

            </blockquote>

            <!-- <p><cite><?= $commentary["Content"]; ?></cite></p> -->


        <?php endforeach; ?>

        <!-- faire une session pour mettre un ocmmentaire -->

        <form action="">
            <label for="">Mettez votre mot ;) il faudra qu'il soit validé par un admin pour apparaitre.
            </label>
            <input type="zonetext">
        </form>


    </div>


</section>