<section class="quiz box">

    <h1>Fin du jeu</h1>
    <ul>
        <p>Bravo ! Vous avez fini ce super <span class="golden-text">Q</span>ui<span class="purple-text">z</span></p>
        <p>Nous espérons que vous aurez apprécié.</p>
        <p>Vous pouvez maintenant refaire les questions jusqu'à ce que vous atteignez les 100% d'avancement :).</p>
        <p>A bientôt pour une suite!</p>
        <p>ACo</p>


        <!-- LIENS RETOUR LISTE TOPICS & TOPIC SUIVANT -->
        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=topic&task=index&topic=1"><button>Retour à la liste des Topics</button></a>

    </ul>
</section>