<section class="quiz box">
	<div class="detail-categorie">
		<h1>Bienvenue sur ce super Quiz!</h1>

		<p><span class="golden-text">P</span>ou<span class="purple-text">r</span> profiter de l'expérience du site <strong>nous vous invitons à vous inscrire</strong> en cliquant sur le lien ci-dessous.</p>

		<p>Cela vous permettra entre autres de sauvegarder vos résultats aux questions, pouvoir les comparer avec vos amis dans le classement, mettre des commentaires sur le Livre d'Or, pleins d'autres surprises et pourquoi pas si un jour vous avez l'honneur de devenir administrateur créer vos propres topics et questions.</p>
		<p>Une fois votre compte créé, merci de vous y connecter.</p>
		<p>Amusez vous bien ! <i class="fas fa-glass-cheers"></i></p>


		<a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=signUpForm" class="button-like">S'inscrire</a>
		<a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=loginForm" class="button-like">Se Connecter</a>

	</div>

</section>