<section class="quiz box">
	<div class="detail-categorie">
		<h1>Bienvenue sur ce super Quiz!</h1>

		<p><span class="golden-text">P</span>ou<span class="purple-text">r</span> profiter un maximum du site, pouvoir compter les scores, pouvoir les comparer avec ses amis, mettre des commentaires, en plus de répondre à ces supers questions, nous vous invitons à vous inscrire, en cliquant sur le lien ci-dessous ( ou dans le menu Mon Compte en haut à droite ).</p>


		<a href="#modalSignUp"><button>S'inscrire</button></a>
		<a href="#modalLogin"><button>Se Connecter</button></a>
		<!-- <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=topic&task=index&topic=1&indexQuestion=1"><button>Accéder directement aux topics</button></a>  -->




	</div>

</section>