<section class="quiz box ">

    <h1><i class="fas fa-home"></i> Accueil / Mode d'emploi</h1>
    <div class="detail-categorie">
        <p>Bienvenue !</p>
        <p>Courtes explications sur le fonctionnement du site avant de commencer.</p>
        <p>Les Questions sont rangées par Topic, <strong>pour commencer il faut choisir un Topic</strong> en appuyant
            sur "Topics" dans le menu en haut de la page.</p>
        <p>Vous pouvez laisser un commentaire dans la partie Explorer/Livre D'Or du site.</p>
        <p>Vous pouvez modifier vos Informations en allant dans Mon Compte/Mes Informations, ou vous Déconnecter en
            cliquant sur Mon Compte / Deconnexion.</p>
        <p>Si vous êtes perdus dans le site, cliquez sur le logo QuiZ by ACo en haut à gauche, il vous ramènera ici au
            mode d'emploi.</p>
        <p>Plus vous répondez juste aux Questions, plus votre Niveau augmente. </p>
        <p>Votre Niveau affiché en dessous de votre photo de profil dépend de chacun des Scores que vous avez eu à
            chaque Topic, et il est mis à jour uniquement lorsqu'un Topic est terminé.</p>
        <p>Vous pouvez voir votre Classement parmi tous les utilisateurs dans la partie Classement Mondial.</p>
        <p>Les différents Niveaux que vous pouvez atteindre sont : </p>
    </div>
    <ul class="ceintures">
        <li>Ceinture Blanche &lt; 10%</li>
        <li>Ceinture Jaune &lt; 20%</li>
        <li>Ceinture Orange &lt; 30%</li>
        <li>Ceinture Verte &lt; 50%</li>
        <li>Ceinture Bleue &lt; 60%</li>
        <li>Ceinture Marron &lt; 80%</li>
        <li>Ceinture Noire &lt; 100%</li>
        <li>Ceinture Ultime = 100%</li>
    </ul>
    <p>Exemples de niveau : </p>
    <div class="ceintures">
        <p class="avancement">26 %</p>
        <p class="avancement">41 %</p>
        <p class="avancement">55 %</p>
        <p class="avancement">64 %</p>
    </div>

    <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=topic&task=index&topic=1&indexQuestion=1" class="button-like">OK J'ai compris! Démarrons le QuiZ !</a>

</section>