<section class="quiz box">

    <h1>Mode d'emploi</h1>
    <p>Super !</p>
    <p>Courtes explications sur le fonctionnement du site avant de commencer.</p>
    <p>Les Questions sont rangées par Topic, pour démarrer il faut choisir un Topic en appuyant sur "Topics" dans le menu en haut de la page.</p>
    <p>Vous pouvez laisser un commentaire dans la partie Explorer/Livre D'Or du site.</p>
    <p>Vous pouvez modifier vos Informations en allant dans Mon Compte/Mes Informations, ou vous Déconnecter en cliquant sur Deconnexion.</p>
    <p>Si vous êtes perdus dans le site, cliquez sur le logo QuiZ by ACo en haut à gauche, il saura toujours vous remettre dans le bon chemin.</p>
    <p>Plus vous répondrez juste aux Questions, plus votre Niveau augmente. Votre score est mis à jour uniquement lorsqu'un Topic est terminé.</p>
    <p>Vous pouvez voir votre Classement dans la partie Classement Mondial.</p>
    <p>Les différents Niveaux que vous pouvez atteindre sont : </p>
    <ul class="ceintures">
        <li>Ceinture Blanche < 10%</li>
        <li>Ceinture Jaune < 20%</li>
        <li>Ceinture Orange < 30%</li>
        <li>Ceinture Verte < 50%</li>
        <li>Ceinture Bleue < 60%</li>
        <li>Ceinture Marron < 80%</li>
        <li>Ceinture Noire < 100%</li>
        <li>Ceinture Ultime = 100%</li>

    </ul>
    <p>Exemples de niveau : </p>
    <div class="ceintures">
        <p class="avancement">14 %</p>
        <p class="avancement">26 %</p>
        <p class="avancement">38 %</p>
        <p class="avancement">55 %</p>
        <p class="avancement">64 %</p>
        <p class="avancement">85 %</p>
    </div>


    <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=topic&task=index&topic=1&indexQuestion=1"><button>Accéder directement aux topics</button></a>


</section>




<!-- /// FICHIER INUTILE FINALEMENT -->