<section class="quiz box page-main">

    <h1>Mode d'emploi</h1>
    <p>Super !</p>
    <p>Courtes explications sur le fonctionnement du site avant de commencer</p>
    <p>Vous progressez avec votre score au fur et à mesure que vous completez les questions par topics.</p>
    <p>Vous pouvez choisir le thème des questions en appuyant sur Topics dans le menu en haut de la page (ou en appuyant sur le bouton ci-dessous). </p>
    <p>Vous pouvez voir où vous en etes en appuyant sur Score dans le menu en haut de la page.</p>
    <p>Vous pouvez modifier vos informations ou vous déconnecter en allant dans Mon Compte dans le menu en haut de la page.</p>
    <p>Si vous êtes perdus dans le site, cliquez sur le logo QuiZ by ACo en haut à gauche ;) il saura vous remettre dans le bon chemin.</p>
    <p>Les différents niveaux que vous pouvez atteindre dans votre Avancement :</p>
    <ul class="ceintures">
        <li>Ceinture Blanche < 10%</li>
        <li>Ceinture Jaune < 20%</li>
        <li>Ceinture Orange < 30%</li>
        <li>Ceinture Verte < 50%</li>
        <li>Ceinture Bleue < 60%</li>
        <li>Ceinture Marron < 80%</li>
        <li>Ceinture Noire < 100%</li>
        <li>Ceinture Ultime ??? Surprise = 100%</li>

    </ul>


    <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=topic&task=index&topic=1&indexQuestion=1"><button>Accéder directement aux topics</button></a>


</section>




<!-- /// FICHIER INUTILE FINALEMENT -->