<section class="quiz box rankings">
    <h1>Le Classement ( Mondial ) <i class="fas fa-trophy"></i></h1>
    <table>
        <thead>
            <tr>
                <th>Rang</th>
                <th>Score</th>
                <th>Pseudo</th>
                <th>Avatar</th>
                <th>Dernière connexion le</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tplVars['userAndScoreList'] as $key => $user) : ?>
            <tr>
                <td><?= $key + 1; ?></td>
                <td class="avancement"><?= number_format(($user['TotalScore'] / (($tplVars['numberOfQuestions'])) * 100)); ?> %</td>
                <td><?= $user['Pseudo']; ?></td>
                <td><img src="<?= $user['Image']; ?>" alt="image de l'utilisateur"></td>
                <td><?= $user['LastConnectedDate']; ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>