<section class="quiz box topic">
    <h1>Liste des Topics</h1>

    <ul>

        <?php foreach ($tplVars['topics'] as $key => $topic) : ?>




            <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=question&task=index&topic=<?= $topic['Id']; ?>&indexQuestion=1"><button><i class="fas fa-sun"></i> <?= $topic['Name']; ?></button></a></li>


            <!-- Affichage des détails du topic, date et créateur -->

            <!-- permet de choper la date, en enlevant l'heure -->
            <?php $date = explode(" ", $topic['CreatedAt']); ?>


            <p><cite>Topic créé le <?= $date[0]; ?> par <?= $tplVars['topicCreatedBy'][$key] ?> </cite></p>


            <!-- Affichage du score par topic  -->

            <?php

            // Si le score est pâs défini dans la bdd, ca affiche que "ca n'a pas été joué" et non 0
            if (!isset($tplVars['scoresByTopic'][$key]['ScoreByTopic']))
                $score = 'Topic pas encore joué';
            else
                $score = $tplVars['scoresByTopic'][$key]['ScoreByTopic'];
            ?>

            <p class="results">Score : <span class="golden-text"><?= $score; ?></span> / <span class="purple-text">5</span> points</p>

            <!-- <?= var_dump($tplVars['scoresByTopic'][$key]['ScoreByTopic']); ?> -->




        <?php endforeach; ?>


    </ul>


    <p>De futurs topics seront à venir... :)</p>


</section>