<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="https://thumbs.dreamstime.com/z/smiley-asiatique-5856320.jpg" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="assets/css/normalize.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <title>QuiZ By ACo</title>
</head>

<body>

<!-- HEADER -->
    <header class="header">
        <div class="container display">

            <!-- Logo Quiz -->



            <a href="<?= $tplVars['WWW_URL']; ?>index.php">
                <img src="assets/images/logo-2.svg" alt="logo-quiz-fait-par-moi" />
            </a>




            <!-- MENU DE NAVIGATION -->
            <nav>
                <ul>


                    <!-- MENU DE NAVIGATION : EXPLORER -->
                    <li class="selected">
                        <a href="<?= $tplVars['WWW_URL']; ?>index.php">
                            <i class="fab fa-wpexplorer"></i><br>
                            Explorer</a>
                        <ul>
                            <li class="selected"><a href="<?= $tplVars['WWW_URL']; ?>index.php">Accueil</a></li>
                            <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=commentary&task=index">Livre d'Or</a></li>
                            <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=about">A propos de Quiz by ACo</a></li>
                        </ul>
                    </li>


                    <!-- MENU DE NAVIGATION : TOPICS -->
                    <li>
                        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=topic&task=index&topic=1">
                            <i class="fas fa-seedling"></i><br>
                            Topics
                        </a>
                        <ul>
                            <?php foreach ($tplVars['topics'] as $topic) : ?>
                                <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=question&task=index&topic=<?= $topic['Id']; ?>&indexQuestion=1"><i class="fas fa-sun"></i><?= $topic['Name']; ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </li>

                    <!-- MENU DE NAVIGATION : CLASSEMENT -->
                    <li>
                        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=rankings">
                            <i class="fas fa-poll-h"></i><br>
                            Classement</a>
                        <ul>
                            <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=rankings">Classement ( Mondial bien sûr )</a></li>
                            <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=topic&task=index&topic=1">Mes résultats par Topic</a></li>
                        </ul>
                    </li>

                    <!-- MENU DE NAVIGATION : MON COMPTE -->
                    <li><a href="#">
                            <i class="fas fa-user-circle"></i><br>
                            Mon Compte</a>
                        <ul>
                            <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=create&topic=1&indexQuestion=1#modalSignUp">S'inscrire</a></li>
                            <li><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=login&topic=1&indexQuestion=1#modalLogin">Se Connecter</a></li>
                            <li><a href="#">Mes informations</a></li>
                            <li><a href="libraries/Views/layoutAdmin.html">Administrateur (BackOffice)</a></li>
                            <li><a href="<?= $tplVars['WWW_URL']; ?>libraries/Out.php">Déconnexion</a></li>
                        </ul>
                    </li>
                </ul>


            </nav>


        </div>
    </header>

<!-- MAIN -->
    <main class="main">


        <!-- faire apparaitre des flashs? -->

        <div class="alert-section" id="zonedenotification">

            <?php if (\Session::hasFlashes('error')) : ?>
                <div class="alert alert-element alert-danger is-active">
                    <div class="icon">
                        <img src="https://images-na.ssl-images-amazon.com/images/I/616t1av6pjL._AC_SL1200_.jpg" alt="notification icon" />
                    </div>
                    <div class="text">
                        <?php foreach (\Session::getFlashes('error') as $message) : ?>
                            <p><?= $message ?></p>
                        <?php endforeach ?>
                    </div>
                </div>
            <?php endif ?>

            <?php if (\Session::hasFlashes('success')) : ?>
                <div class="alert alert-element alert-success is-active">
                    <div class="icon">
                        <img src="https://images-na.ssl-images-amazon.com/images/I/616t1av6pjL._AC_SL1200_.jpg" alt="notification icon" />
                    </div>
                    <div class="text">
                        <?php foreach (\Session::getFlashes('success') as $message) : ?>
                            <p><?= $message ?></p>
                        <?php endforeach ?>
                    </div>
                </div>
            <?php endif ?>

        </div>







        <div class="container display__main">
            <aside>


                <!-- ASIDE BOX 1 POUR LE PROFIL DE l'USER -->
                <div class="identification box">
                    <h2>Profil</h2>
                    <?php
                    //si je suis connecté, j'affiche image + pseudo + score
                    //sinon j'affiche pas connecté
                    if (\Session::isConnected()) :
                    ?>
                        <img src="<?= $_SESSION['user']['AvatarURL']; ?> alt=" profil picture">

                        <?php
                            $text1 = "Je vois que l'on se porte bien, bienvenue";
                            $text2 = "Je vois qu'on pousse à la salle, bienvenue";
                            $text3 = "Très belle dégaine, bienvenue";
                            $text4 = "Quel regard, bienvenue";
                            $text5 = "Votre mine est radieuse, bienvenue";

                            $variable = rand(1, 5);

                            switch ($variable) {
                                case 1:
                                    $text = $text1;
                                    break;
                                case 2:
                                    $text = $text2;
                                    break;
                                case 3:
                                    $text = $text3;
                                    break;
                                case 4:
                                    $text = $text4;
                                    break;
                                case 5:
                                    $text = $text5;
                                    break;
                            }
                        ?>

                        <h3><?= $text ?><span class="golden-text"><?= $_SESSION['user']['Pseudo']; ?></span></h3>

                        <!-- AVANCEMENT DE L'UTILISATEUR -->
                        <p><span class="golden-text">A</span>vancement dans le sit<span class="purple-text">e</span> (mis à jour à la fin d'un topic) :</p>
                        <p class="avancement"><?= $tplVars['progressionUser']; ?> %</p>


                    <?php
                    else :
                    ?>
                        <p>Utilisateur non connecté :(</p>
                    <?php
                    endif;
                    ?>
                </div>




                <!-- ASIDE BOX 2 POUR LES COMMENTAIRES  -->
                <div class="commentary_box box">
                    <h2>Commentaires</h2>
                    <p>Aidez moi à améliorer le site, mettez votre avis dans l'espace Explorer/Votre Avis ;)</p>
                    <div class="commentary_box_quotes">
                        <?php foreach ($tplVars['commentaries'] as $key => $commentary) : ?>
                            <blockquote>
                                <cite>"<?= $commentary["Content"]; ?>"</cite>

                                <!-- permet de choper la date, en enlevant l'heure -->
                                <?php $date = explode(" ", $commentary['Created_at']); ?>
                                <p class="commentary__author">le <?= $date[0]; ?> par <?= $tplVars['commentaryCreatedBy'][$key] ?></p>
                            </blockquote>
                        <?php endforeach; ?>
                    </div>
                </div>
            </aside>

            <!-- LE PAGE CONTENT -->
            <?= $pageContent ?>

        </div>









        <!-- LES MODALES-->

        <!-- Modale pour s'inscrire' -->
        <div class="modal-bg" id="modalSignUp">
            <div class="modal-content">
                <a href="index.php" class="close">&times;</a>
                <p>Inscrivez vous pour profiter au maximum du super <span class="golden-text">Q</span>ui<span class="purple-text">Z</span>!</p>

                <?php if (!empty($message)) : ?>
                    <p><?= $message; ?></p>
                <?php endif; ?>

                <form action="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=create" method="POST">
                    <label for="email"><i class="fas fa-envelope"></i> Email (aucun spam garanti)</label>
                    <input type="email" name="email" id="email" placeholder="email" />
                    <label for="pseudo"><i class="fas fa-male"></i> Pseudo</label>
                    <input type="text" name="pseudo" id="pseudo" placeholder="pseudo" />
                    <label for="password"><i class="fas fa-lock"></i> Mot de passe (sera crypté en interne pour une bonne sécurité)</label>
                    <input type="text" name="password" id="password" placeholder="password" />
                    <label for="email"><i class="fas fa-camera-retro"></i> Votre Avatar (pour vous reconnaître)</label>
                    <div class="display_flex">
                        <input type="radio" name="avatar" value="0" id="avatar1" /><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BNTczMzk1MjU1MV5BMl5BanBnXkFtZTcwNDk2MzAyMg@@._V1_UY256_CR2,0,172,256_AL_.jpg" alt="WillSmith">
                        <input type="radio" name="avatar" value="1" id="avatar2" /><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMjUzZTJmZDItODRjYS00ZGRhLTg2NWQtOGE0YjJhNWVlMjNjXkEyXkFqcGdeQXVyMTg4NDI0NDM@._V1_UY256_CR42,0,172,256_AL_.jpg" alt="GalGadot">
                        <input type="radio" name="avatar" value="2" id="avatar3" /><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BOWViYjUzOWMtMzRkZi00MjNkLTk4M2ItMTVkMDg5MzE2ZDYyXkEyXkFqcGdeQXVyODQwNjM3NDA@._V1_UY256_CR36,0,172,256_AL_.jpg" alt="AdamDriver">
                        <input type="radio" name="avatar" value="3" id="avatar4" /><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BNjk5NjE5NTczMV5BMl5BanBnXkFtZTcwODI0OTM0NA@@._V1_UY256_CR4,0,172,256_AL_.jpg" alt="Effy">
                        <input type="radio" name="avatar" value="4" id="avatar5" /><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BOTU2MTI0NTIyNV5BMl5BanBnXkFtZTcwMTA4Nzc3OA@@._V1_UX172_CR0,0,172,256_AL_.jpg" alt="ChrisHemsworth">
                    </div>
                    <button type="submit">S'inscrire!</button>
                </form>
            </div>
        </div>

        <!-- Modale pour login -->
        <div class="modal-bg" id="modalLogin">
            <div class="modal-content">
                <a href="index.php" class="close">&times;</a>
                <p>Merci de renseigner vos identifiants <span class="golden-text">Q</span>ui<span class="purple-text">Z</span>!</p>
                <form action="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=login" method="POST">
                    <label for="email"><i class="fas fa-envelope"></i> Email</label>
                    <input type="email" name="email" id="email" placeholder="email" />
                    <label for="password"><i class="fas fa-lock"></i> Mot de passe</label>
                    <input type="text" name="password" id="password" placeholder="password" />
                    <button type="submit">Se Connecter</button>
                </form>
            </div>
        </div>

    </main>



<!-- FOOTER -->
    <footer class="footer">
        <div class="container signature">
            <p>Projet réalisé par : <a href="https://www.linkedin.com/in/alexandre-connangle-6221a558/">Alexandre Code</a>.</p>
            <p>En POO en respectant la structure MVC.</p>
            <p>Technologies utilisées : HTML, CSS, SASS, JAVASCRIPT, PHP, MYSQL.</p>
            <p><small>Mentions légales ACo ©</small><small> - Jan/Fev 2021.</small></p>
        </div>

    </footer>


    <!-- SCRIPTS -->
    <script src="assets/js/navbar.js"></script>
    <script src="assets/js/answers.js"></script>
    <script src="assets/js/notifications.js"></script>

</body>

</html>