<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="<?= $tplVars['WWW_URL']; ?>assets/images/quiz-icon-made-by-me.svg" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="assets/css/normalize.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <title>QuiZ By ACo</title>
</head>
<body>

    <!-- HEADER -->
    <?php include('layout/header.php'); ?>

    <!-- MAIN -->
    <main class="main">
        <!-- Faire apparaitre les notifications success/echec -->
        <?php include('layout/notifications.php'); ?>
        <!-- Partie principale du main qui contient l'aside et la box principale -->
        <div class="container display__main">
            <!-- ASIDE qui contient BOX 1 PROFIL et BOX 2 COMMENTAIRES -->
            <?php include('layout/aside.php'); ?>
            <!-- PAGE CONTENT - BOX PRINCIPALE QUI CONTIENT LE TEMPLATE -->
            <?= $pageContent ?>
        </div>
        <!-- LES 2 MODALES LOGIN ET SIGNUP -->
        <?php include('layout/modals.php'); ?>
    </main>

    <!-- FOOTER -->
    <?php include('layout/footer.php'); ?>

    <!-- SCRIPTS -->
    <script src="assets/js/scoreColorisation.js"></script>
    <script src="assets/js/answers.js"></script>
    <script src="assets/js/notifications.js"></script>
</body>
</html>