<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Back Office Questionnaire</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://tutos.ies-sud.fr/wp-content/uploads/2018/03/Picto_admin_reglages-1.png" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="assets/admin/css/normalize.css">
    <link rel="stylesheet" href="assets/admin/css/styleAdmin.scss">
</head>

<body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid d-flex justify-content-end align-items-center">
            <a class="navbar-brand" href="#">BackOffice du Quiz by ACo</a>
            <h1 class="navbar-text"><?= $tplVars['page_title']; ?></h1>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto d-flex justify-content-end align-items-center w-100">
                    <li class="nav-item w-33 mx-2">
                        <a class="nav-link d-block mx-2" href="<?= $tplVars['WWW_URL']; ?>index.php"><i class="fas fa-arrow-left"></i> Revenir au site normal</a>
                    </li>

                    <li class="nav-item w-33 mx-2">
                        <a class="nav-link d-block" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=out"><i class="fas fa-power-off"></i> Déconnexion</a>
                    </li>

                    <li class="nav-item w-33 mx-2">
                        <div class="">
                            <img alt="Avatar de <?= \Session::getFirstName(); ?>" src="<?= $_SESSION["user"]["AvatarURL"]; ?>assets/admin/images/avatar.png" width="48">
                            <p><?= \Session::getFirstName(); ?></p>
                            <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Faire apparaitre les flashs -->
    <div class="alert-section" id="zonedenotification">
        <?php if (\Session::hasFlashes('error')) : ?>
            <div class="alert alert-element alert-danger is-active">
                <div class="icon">
                    <!-- <img src="https://images-na.ssl-images-amazon.com/images/I/616t1av6pjL._AC_SL1200_.jpg" alt="notification icon" /> -->
                </div>
                <div class="text">
                    <?php foreach (\Session::getFlashes('error') as $message) : ?>
                        <p><?= $message ?></p>
                    <?php endforeach ?>
                </div>
            </div>
        <?php endif ?>

        <?php if (\Session::hasFlashes('success')) : ?>
            <div class="alert alert-element alert-success is-active">
                <div class="icon">
                    <!-- <img src="https://images-na.ssl-images-amazon.com/images/I/616t1av6pjL._AC_SL1200_.jpg" alt="notification icon" /> -->
                </div>
                <div class="text">
                    <?php foreach (\Session::getFlashes('success') as $message) : ?>
                        <p><?= $message ?></p>
                    <?php endforeach ?>
                </div>
            </div>
        <?php endif ?>
    </div>

    <div class="container-fluid">
        <div class="row d-md-flex d-block">
            <aside class="col-md-3 p-3 bg-light">
                <nav class="nav nav-pills flex-column">
                    <a class="nav-item nav-link" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\Dashboard&task=index"><i class="fa fa-home"></i> Tableau de bord</a>
                    <a class="nav-item nav-link" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\User&task=index"><i class="fas fa-address-card"></i> Gestion des utilisateurs</a>
                    <a class="nav-item nav-link" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\Topic&task=index"><i class="fa fa-globe"></i> Gestion des topics</a>
                    <a class="nav-item nav-link" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\Question&task=index"><i class="fab fa-algolia"></i> Gestion des questions</a>
                    <a class="nav-item nav-link" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\Commentary&task=index"><i class="fas fa-quote-right"></i> Gestion des commentaires</a>
                </nav>
            </aside>
            <main class="col-md-9 p-3">
                <!-- page content -->
                <?= $pageContent ?>
                <!-- page content -->
            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
</body>

</html>