<!-- list des commentaires -->

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Commentaire</th>
                <th>Auteur</th>
                <th>Date de publication</th>
                <th>Affichage sur le site</th>
                <th>Modifier Affichage</th>
                <!-- <th>Image</th> -->
                <th class="text-right" width="20%">Supprimer</th>
            </tr>
        </thead>
        <tbody>
            <!-- boucle sur les tags -->
            <?php foreach ($tplVars['list'] as $item) : ?>
            <tr>
                <!-- <td><?= var_dump($item); ?></td> -->
                <td><?= htmlspecialchars($item['Id']); ?></td>
                <td><?= htmlspecialchars($item['Content']); ?></td>
                <td><?= htmlspecialchars($item['Pseudo']); ?></td>
                <td><?= htmlspecialchars($item['Created_at']); ?></td>

                <td>
                    <?php
                        //afficher oui si admin sinon afficher non
                        if (intval($item['Status']) == 1) :
                            echo 'Oui';
                        else :
                            echo 'Non';
                        endif;
                        ?>
                </td>
                <td>
                    <a class="btn btn-sm btn-outline-secondary"
                        href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud']; ?>&task=updateCommentStatus&id=<?= intval($item['Id']); ?>"><i
                            class="fa fa-pencil"></i> Modifier</a>
                </td>

                <td class="text-right">
                    <a class="btn btn-sm btn-outline-danger"
                        href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud']; ?>&task=delete&id=<?= intval($item['Id']); ?>"><i
                            class="fa fa-archive"></i> Supprimer</a>

                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>