<form enctype="multipart/form-data"
    action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud']; ?>&task=update" method="POST">
    <input type="hidden" name="id" value="<?= intval($_GET['id']); ?>" />
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center my-4">
        <a class="btn btn-outline-secondary"
            href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud']; ?>&task=index"><i
                class="fa fa-times"></i> Annuler les modifications</a>
        <button class="btn btn-primary"><i class="fa fa-check"></i> Valider et enregistrer</button>
    </div>

    <fieldset class="p-3 bg-light">
        <div class="form-group mb-2">
            <label for="inputState" class="col-form-label form-label">Choix du Topic</label>
            <div>
                <select id="inputState" class="form-select" name="Topic_Id"
                    value="<?= $tplVars['list'][0]['Topic_Id']; ?>">
                    <?php foreach ($tplVars['topics'] as $topic) : ?>
                    <option value="<?= $topic['Id'] ?>"><?= $topic['Id'] . ". " . $topic['Name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group mb-2">
            <label for="IndexQuestion" class="col-form-label">IndexQuestion - n° de la Question dans le topic : indiquer
                "1" ou "2" ou "3" ou "4" ou "5" etc.</label>
            <div>
                <input type="text" class="form-control" name="IndexQuestion"
                    value="<?= $tplVars['list'][0]['IndexQuestion']; ?>">
            </div>
        </div>
        <div class="form-group mb-2">
            <label for="Question" class="col-form-label">Question - redigez son intitulé complet</label>
            <div>
                <input type="text" class="form-control" name="Question" value="<?= $tplVars['list'][0]['Question']; ?>">
            </div>
        </div>
        <div class=" form-group mb-2">
            <label for="Answers" class="col-form-label">Answers - écrire les réponses de la sorte (LA SYNTAXE EST
                IMPORTANTE): "A. Mettre ici la réponse A - B. Mettre ici la réponse B - C. Mettre ici la réponse C - D.
                Mettre ici la réponse D"</label>
            <div>
                <input type="text" class="form-control" name="Answers" value="<?= $tplVars['list'][0]['Answers']; ?>">
            </div>
        </div>
        <div class="form-group mb-2">
            <label for="IndexGoodAnswer" class="col-form-label">IndexGoodAnswer - indiquez qu'elle réponse est la bonne
                : "1" ou "2" ou "3" ou "4".</label>
            <div>
                <input type="text" class="form-control" name="IndexGoodAnswer"
                    value="<?= $tplVars['list'][0]['IndexGoodAnswer']; ?>">
            </div>
        </div>
        <div class="form-group mb-2">
            <label for="Image" class="col-form-label">URL de l'image - mettre le lien directement d'une image en lien
                avec la question</label>
            <div>
                <input type="text" class="form-control" name="Image" value="<?= $tplVars['list'][0]['Image']; ?>">
            </div>
        </div>
    </fieldset>

</form>